### ISSUE TITLE
Create aggregate operation

### ISSUE THREAD

**Issue by Farenheith** [codibre/fluent-iterable#25]
The aggregate operation consists in a operation where multiple aggregations can be applied. The idea of use is like this:

```ts
const result = fluent(origin)
  .aggreagate((x) => ({
    sumValue: sum((x) => x.value),
    maxValue: max((x) => x.value),
    minValue: min((x) => x.value),
    firstValue: first((x) => x.value),
    lastValue: last((x) => x.value),
    modularSumValue: mod(sum((x) => x.value)),
  }));
```

The advantage of this is that we can get many aggregations results with just one loop operation.
Ideally, it must exist some mechanism to identify uniquely search sum call, for example, so the aggregation can separate one call from another under the hood.

**Comment by dlecan** [comment]
Did you implement this @Farenheith ?

**Comment by Farenheith** [comment]
> Did you implement this @Farenheith ?

Actually, no. As far as I remember, I got on some technical issues to make it work, and I decided to give up on this 
Do you think it's worth it? I can reopen the issue and take a look again on this in my spare time.

Maybe at this point an extension library could be written to do it.

**Comment by dlecan** [comment]
I was just curious to see how that could be implemented 😇
In one loop… I don’t get the algorithm

**Comment by Farenheith** [comment]
Lol.
Well, when I took a look at this, I couldn't make it work as described either. I figured out that something like this could be more feasible:
```ts
const result = fluent(origin)
  .aggregate((x, agg) => ({
    sumValue: agg.sum('sumValue', (x) => x.value),
    maxValue: agg.max('maxValue', (x) => x.value),
    minValue: agg.min('minValue', (x) => x.value),
    firstValue: agg.first('firstValue', (x) => x.value),
    lastValue: agg.last('lastValue', (x) => x.value),
    modularSumValue: agg.sum('modularSumValue', (x) => x.value) % mod,
  }));
```

This way I could control the needed scope for each operation with the agg parameter.

I just didn't follow with this because I thought it was too much complexity to keep on the core of the lib for something that can be easily done with reduce

**Comment by Farenheith** [comment]
@dlecan I managed to find a simpler solution to implement this feature pretty close to the proposed format and just opened a pull request

**Comment by Farenheith** [comment]
With the creation of the branch operation this idea of feature may not be as useful anymore. I'll check it out ASAP with a benchmark to see if there's any advantage of aggregate over it

**Comment by Farenheith** [comment]
This operation has lost to branch:
```
separated x 35,916 ops/sec ±1.28% (91 runs sampled)
manual branch x 45,482 ops/sec ±0.52% (94 runs sampled)
banching x 80,455 ops/sec ±4.94% (34 runs sampled)
aggregate x 43,233 ops/sec ±0.52% (93 runs sampled)
```

Closing it
