### ISSUE TITLE
Implement method isDinstinct

### ISSUE THREAD

**Issue by Farenheith** [codibre/fluent-iterable#9]
**isDistinct** must receive two optional parameters:
* **mapper:** A mapper to return the value to be checked uniqueness. The default must be the identity function
*  **threshold:** The max number of occurrences accepted. The default must be 1.

It must be a resolving operation.
It must return true when each mapped value occurs at most the informed threshold value and false otherwise.

Also, update method **distinct** to accept the same parameter **threshold**

**Comment by Farenheith** [comment]
@danstarns could you help me? I'm not satisfied with the name of this method, I guess my English is struggling to find a better one lol.
Do you have any suggestions to name this operation?

**Comment by danstarns** [comment]
@Farenheith I'm thinking of naming it after something similar to lodash [`uniqBy`](https://lodash.com/docs/4.17.15#uniqBy) or even `unionBy`.

```ts
fluent(generator())
    .uniqBy((x) => x._id)
```

```ts
fluent(alphabet())
    .uniqBy(
        (x) => x.letter,
        {
            threshold: 1
        }
    );
```

```ts
// using proper english
fluent(generator())
    .uniqueBy((x) => x._id)
```

**Comment by danstarns** [comment]
Looking back on my code example I also suggest making the `mapper` either a function or string, that's, of course, **if I am interpreting this feature correctly?**

```ts
fluent(alphabet())
    .uniqBy("letter"); // (x) => x.letter
```

**Comment by Farenheith** [comment]
**uniqueBy** sounds more like a method that would remove all repetitions, don't you think?
Also, the main issue I'm having with the name is the word **unique**. I don't know if it plays well with the threshold parameter
Like... do you think this looks like a good behavior?
```typescript
fluent([{ a: 1 }, { a: 1 }, { a: 2}]).isUnique((x) => x.a, 2) // returns true
```

**Comment by danstarns** [comment]
@Farenheith Now you say it I agree! I missed that the function would return a boolean. What about `isUnion` ?

**Comment by Farenheith** [comment]
I'm not sure. I thought in another one... **isDistinct**. There is already a method called **distinct** which remove repetitions, so, it may play well

**Comment by danstarns** [comment]
I think `isDistinct` works well

**Comment by Farenheith** [comment]
@danstarns 
Thank you! I also like your suggestion of this method accepting string values. Though no other method in this library have this option yet, I see many scenarios where this may be useful

**Comment by danstarns** [comment]
@Farenheith Cool stuff 🍻

**Comment by danstarns** [comment]
Using some examples below, How would nested objects and arrays be treated with this feature?

```ts
const nested = { distict: 1 };

const item1 = { a: 1, nested };
const item2 = { a: 2, nested };
const item3 = { a: 3, nested };

fluent([item1, item2, item3]).isDistinct((x) => x.nested) // returns ??
```

```ts
const nested = [];

const item1 = { a: 1, nested };
const item2 = { a: 2, nested };
const item3 = { a: 3, nested };

fluent([item1, item2, item3]).isDistinct((x) => x.nested) // returns ??
```

```ts
const item1 = { a: 1, nested: { distict: 1 } };
const item2 = { a: 2, nested: { distict: 1 } };
const item3 = { a: 3, nested: { distict: 1 } };

fluent([item1, item2, item3]).isDistinct((x) => x.nested) // returns ??
```

**Comment by Farenheith** [comment]
> Using some examples below, How would nested objects and arrays be treated with this feature?
> 
> ```ts
> const nested = { distict: 1 };
> 
> const item1 = { a: 1, nested };
> const item2 = { a: 2, nested };
> const item3 = { a: 3, nested };
> 
> fluent([item1, item2, item3]).isDistinct((x) => x.nested) // returns ??
> ```
> 
> ```ts
> const nested = [];
> 
> const item1 = { a: 1, nested };
> const item2 = { a: 2, nested };
> const item3 = { a: 3, nested };
> 
> fluent([item1, item2, item3]).isDistinct((x) => x.nested) // returns ??
> ```

In both examples, it would return false. Also, is important to notice that, as soon as the result is determined, the iteration will end, ie, it'd only iterate over two value in these cases.

> 
> ```ts
> const item1 = { a: 1, nested: { distict: 1 } };
> const item2 = { a: 2, nested: { distict: 1 } };
> const item3 = { a: 3, nested: { distict: 1 } };
> 
> fluent([item1, item2, item3]).isDistinct((x) => x.nested) // returns ??
> ```

In this case, the return would be true, as each **nested** is a distinct object
